@startuml
title 3.1 Check Travel Flow (Real-Time Integration)

|User/Client|
start
:Input Destinasi (ex: Tokyo) & Currency (ex: JPY);
:Kirim Request POST (+ API Key);

|Backend Server|
:Validasi API Key di DB;
if (Key Valid?) then (No)
    :Return 403 Forbidden;
    stop
else (Yes)
    :Update Hits Counter (+1);
    
    fork
        :Request ke WeatherAPI;
        :Get Suhu & Kondisi Langit;
    fork again
        :Request ke Frankfurter API;
        :Get Nilai Tukar IDR;
    end fork
    
    :Jalankan Algoritma Sniper (Gacha);
    :Gabungkan Data (Decision + Weather + Rate);
    :Kirim Response JSON;
endif

|User/Client|
:Tampilkan Hasil Real-time;
stop
@enduml