@startuml
skinparam componentStyle uml2

package "Client Side (Frontend)" {
    [React App (Vite)] as Frontend
}

package "Server Side (Backend)" {
    [Node.js Express Server] as Server
    [Sniper Logic] as Logic
}

database "Internal Data" {
    [MySQL Database] as DB
}

cloud "External Services (3rd Party)" {
    [WeatherAPI.com] as Weather
    [Frankfurter API] as Rates
}

' Relasi
Frontend <--> Server : JSON / HTTP REST
Server <--> DB : Read/Write User & Keys
Server --> Logic : Process Request

' Ini yang BARU: Server nembak ke Luar
Logic <--> Weather : Fetch Real-time Weather
Logic <--> Rates : Fetch Real-time Currency

@enduml